parameters:
    models: AutoRec
    similarity: Cosine
    corruption: [0]
    alpha: [1]
    rank: [50, 100, 200]
    root: [1.0]
    topK: [5, 10, 20]
    iter: 300
    lambda: [0.00001, 0.0001, 0.001, 0.01, 0.1]
    metric: [R-Precision, NDCG, MAP, Precision, Recall]