parameters:
    models: PureSVD
    similarity: Cosine
    corruption: [0]
    alpha: [1]
    rank: [50, 100, 200]
    root: [1.0]
    topK: [5, 10, 20]
    iter: 50
    lambda: [1]
    metric: [R-Precision, NDCG, MAP, Precision, Recall]